# Defines the port where the config server is running so that rest of the services can pick up
# their external props configurations
server:
    port: 9999

spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/rk365/microservices-config.git
                    searchPaths: MASTER_PROPS